import { VibrationTrend } from './VibrationTrend'
import type { Incident, Sensor, SensorState } from '../types/dashboard'

const labels: Record<SensorState, string> = { normal: 'Normal', watch: 'Watch', critical: 'Alarm', offline: 'No signal' }

export function SensorDetail({ sensor, incident }: { sensor?: Sensor; incident?: Incident }) {
  if (!sensor) return <section className="detail-panel empty-detail"><p className="eyebrow">SENSOR DETAIL</p><h2>Waiting for stream</h2><p>Start the producer and API to populate live telemetry.</p></section>
  const lastSeenSeconds = Math.max(0, Date.now() / 1000 - sensor.timestamp)
  return <section className="detail-panel"><div className="detail-heading"><div><p className="eyebrow">{sensor.asset_id} / {sensor.area}</p><h2>{sensor.equipment_name}</h2></div><span className={`pill ${sensor.state}`}>{labels[sensor.state]}</span></div><div className="reading-grid"><div className="primary-reading"><span>VIBRATION</span><strong>{sensor.vibration === null ? '—' : sensor.vibration.toFixed(2)} <small>{sensor.unit}</small></strong><p>{sensor.vibration === null ? 'Latest channel value is missing' : 'Current validated reading'}</p></div><div className="metric"><span>TEMPERATURE</span><strong>{sensor.temperature.toFixed(1)}<small>°C</small></strong><p>Live channel</p></div><div className="metric"><span>HUMIDITY</span><strong>{sensor.humidity === null ? '—' : sensor.humidity.toFixed(1)}<small>%</small></strong><p>Live channel</p></div></div><div className="chart-section"><div className="chart-meta"><div><span>VIBRATION CONDITION · LAST {sensor.trend.length} READINGS</span><strong>Actual signal against learned operating pattern</strong></div><span className="live-label"><i /> LIVE</span></div><VibrationTrend trend={sensor.trend} state={sensor.state} unit={sensor.unit} incident={incident} /><div className="chart-axis"><span>OLDER</span><span>NOW</span></div></div><div className="data-note">Stream ID <b>{sensor.device_id}</b> · Sequence <b>{sensor.sequence_number}</b> · Last message <b>{lastSeenSeconds < 2 ? 'now' : `${Math.round(lastSeenSeconds)}s ago`}</b></div></section>
}
